### ISSUE TITLE
not working functions

### ISSUE THREAD

**Issue by username1234567890987654321** [davidson16807/tectonics.js#35] opened 2019-02-14 07:46 UTC
I noticed that air pressure, precipitation and wind speed are not working.

**Comment by davidson16807** [comment] 2019-02-20 15:57
Confirmed, will look into this.

**Comment by davidson16807** [comment] 2019-03-01 18:44
Looks like the names for a few displays were borked during an earlier batch rename. Will push a fix for this by end of day.

**Comment by davidson16807** [comment] 2019-03-01 23:25
Fixes have been deployed. Let me know if there are any more problems, otherwise I'll close out the issue.

**Closed** 2019-03-03 05:30 UTC
Labels: bug

**Comment by IsaacEthington** [comment] 2019-03-04 23:13
Precipitation still doesn't seem to work. It shows colors, but only the default color lines and they do not change over time.

**Comment by davidson16807** [comment] 2019-03-05 00:17
Nah, that's intended (unfortunately). We still need to work on precipitation. I'll prioritize that in another issue.

**Comment by davidson16807** [comment] 2019-03-05 00:23
Issue #37 is created to address precip. I'm making a call for suggestions there.
